tasks:
  - name: terraform
    before: |
      source ./bin/install_terraform_cli
    #  sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
    #  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    #  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" -y
    #  sudo apt-get update && sudo apt-get install terraform
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli
    #  cd /workspace
    #  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    #  unzip awscliv2.zip
    #  sudo ./aws/install
    #  cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform